spring:
  application:
    name:
      demo
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${YOUR_VALUE_OF_CLIENT_ID}
            client-secret: ${YOUR_VALUE_OF_CLIENT_SECRET}
            scope:
            - read:user
            - user:email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          my-provider:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  